"""empty message

Revision ID: 4ed4160d84d3
Revises: 1a36cb32bf76
Create Date: 2025-10-07 00:13:53.444894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4ed4160d84d3'
down_revision: Union[str, Sequence[str], None] = '1a36cb32bf76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'recipient_role',
               existing_type=mysql.ENUM('all', 'ceo', 'hr', 'finance', 'event_manager', 'employee'),
               type_=sa.Enum('ALL', 'CEO', 'HR', 'FINANCE', 'EVENT_MANAGER', 'EMPLOYEE', 'ADMIN', name='recipientrole', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'recipient_role',
               existing_type=sa.Enum('ALL', 'CEO', 'HR', 'FINANCE', 'EVENT_MANAGER', 'EMPLOYEE', 'ADMIN', name='recipientrole', native_enum=False),
               type_=mysql.ENUM('all', 'ceo', 'hr', 'finance', 'event_manager', 'employee'),
               existing_nullable=False)
    # ### end Alembic commands ###
